### ISSUE TITLE
Testing White vs Black score

### ISSUE THREAD

**Issue by alwey** [ianfab/fishtest#13]
It may be possible to test white score vs black score directly without having to modify the source code.
Recent versions of cutechess-cli support the `-noswap` option. This prevents the players to swap positions/sides.
If a test uses a white-to-move opening suite or position set, e.g. 2moves_v1.epd, or `crazyhouse-p4-f12.epd,` the first engine will allways play the white pieces. If using a "black suite" like `crazyhoude.epd`, it will be the other way round.

Fishtest may relay control of the -noswap option to enable this kind of testing.

**Comment by ianfab** [comment]
Thanks. Yes, that would be an idea to make such testing more convenient. So far all tests with fixed colors were only to find out the scores of each color, so https://github.com/cutechess/cutechess/issues/354 is also kind of related (although both features have their own value and are useful independently), which would allow to collect such stats on all tests.

I plan to add optional disabling of adjudication with the next worker version and the no-swap option would require the exact same way of enabling/disabling the option and passing it to the worker, so that could be done in one go. Apropos, as a note to myself I summarize the things I want to add/fix with the next worker update:
- optional disabling of adjudication
- optional testing without switching colors (no-swap)
- fix books to make them not rely on undocumented support for incomplete FENs

**Comment by alwey** [comment]
@ianfab 

> I plan to add optional disabling of adjudication with the next worker version and the no-swap option would require the exact same way of enabling/disabling the option and passing it to the worker, so that could be done in one go. Apropos, as a note to myself I summarize the things I want to add/fix with the next worker update ...

Great to hear this.  Perhaps you might consider an additional feature that requires control of an option:
- pondering 

I admit, this would be more interesting for fishtest upstream but while there ...

**Comment by alwey** [comment]
> So far all tests with fixed colors were only to find out the scores of each color, so cutechess/cutechess#354 is also kind of related (although both features have their own value and are useful independently), which would allow to collect such stats on all tests.

Of course, this is a related matter and I already have a CLI version with white / black scores. I think the GUI part will be done in a second step.

```
Finished game 1004 (Stockfish 9 64 BMI2 vs Stockfish-test): * {No result}
Score of Stockfish-test vs Stockfish 9 64 BMI2: 229 - 218 - 557  [0.505] 1004
Elo difference: 3.81 +/- 14.33
When playing White: 129 - 98 - 276  [0.531] 503
When playing Black: 100 - 120 - 281  [0.480] 501
White vs Black    : 249 - 198 - 557  [0.525] 1004
Finished match
```

**Comment by alwey** [comment]
@ddugovic @ianfab : As I am no native speaker, I am not sure about the proposed output format /wrt clarity and correctness.

**Comment by ianfab** [comment]
@alwey Nice. For me the output is clear enough. However, I realized that this can anyway not be used in fishtest, since the results are parsed game by game, so the results for the colors would probably have to be deduced from messages like "white wins" or "black loses on time", but since that is not trivial due to custom messages for variants, I will just add the no-swap option.

I am not sure for what the pondering option could be used. Apart from testing the Elo difference with pondering enabled/disabled, I do not see any obvious use case.

**Comment by ddugovic** [comment]
I agree the output is clear enough.

Long term it could be fun/interesting to count all the result messages and print statistics for each of those, for example:

```
...
White vs Black    : 249 - 198 - 557  [0.525] 1004
Threefold repetition: 2
White wins by explosion: 5
White wins by resignation: 10
etc.
Finished match
```

**Comment by alwey** [comment]
@ianfab: 

> I am not sure for what the pondering option could be used. Apart from testing the Elo difference with pondering enabled/disabled, I do not see any obvious use case.

The upstream developers might seize the opportunity and test their time management parameters for games with pondering "on".

@ddugovic :

> Long term it could be fun/interesting to count all the result messages and print statistics for each of those, for example: ...

 I agree very much, this is on my list, recent I opened an issue https://github.com/cutechess/cutechess/issues/355. It might be better to use the term "game termination" instead of "terminated games". This would also include games without irregularities.

**Comment by alwey** [comment]
The cutechess patch mentioned above provides separate totals for Black and White. It is in the master now.

I am preparing a patch for game statistics. The game outcomes are sorted into e.g. different draw types and different types of terminations like timeout, illegal move, disconnect, stalled connection.These can be listed in the result table.

There also is an additional method to list outcomes more freely according to the result comments - as suggested

> Threefold repetition: 2
> White forfeits on time: 1
> White wins by resignation: 10
> White's king exploded: 5
> etc.
> Finished match

Indeed, an excerpt of an output for a round-robin-tournament with active adjudication looks like this:
```
...
Player: stockfish-7
"Draw by 3-fold repetition" :  7
"Draw by adjudication" :  14
"Draw by insufficient mating material" :  4
"Loss: Black wins by adjudication" :  2
"Loss: White wins by adjudication" :  2
"Win: Black wins by adjudication" :  2
"Win: White wins by adjudication" :  5

Player: stockfish-6
"Draw by 3-fold repetition" :  7
"Draw by adjudication" :  14
"Draw by insufficient mating material" :  4
"Loss: Black wins by adjudication" :  2
"Loss: White wins by adjudication" :  2
"Win: Black wins by adjudication" :  2
"Win: White wins by adjudication" :  5
...
```
